name: Install and test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        python setup.py install
        python -c "import mindspore; print(mindspore.__version__)"
        python -c "import tinyms; print(tinyms.__version__)"
        pytest
